name: Lint PRs
on:
  pull_request:
  workflow_dispatch:

jobs:

  hadolint-pr:
    runs-on: ubuntu-latest
    name: PR - Hadolint
    steps:
      - uses: actions/checkout@v4
        # Ignores do not work: https://github.com/reviewdog/action-hadolint/issues/35 is resolved
      - uses: reviewdog/action-hadolint@v1

  shellcheck-pr:
    runs-on: ubuntu-latest
    name: PR - Shellcheck
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master

  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash
  # Special lint to handle reusable workflows requiring an explicit branch.
  # We cannot just reference the current/default but have to make sure it is `master`.
  reusable-workflow_lint-pr:
    runs-on: ubuntu-latest
    name: PR - Reusable workflow linting
    steps:
      # We probably should target this on only workflow changes but the complexity of doing that is a lot more than just letting the grep run.
      - uses: actions/checkout@v4
      # Recursive grep or any workflow using a local reusable workflow but not ending in @main
      - run: |
          if [[ $(grep -R -E 'uses:[ ]*calyptia/enterprise/.github/workflows/.*@[^main].*$' .github/workflows/*.y*ml| wc -l) -gt 0 ]]; then
            echo "Found reusable workflow on non-main branch"
            grep -R -E 'uses:[ ]*calyptia/enterprise/.github/workflows/.*@[^main].*$' .github/workflows/*.y*ml
            exit 1
          fi
          echo "Passed reusable workflow checks"
        shell: bash

  docslint-pr:
    runs-on: ubuntu-latest
    name: PR - Markdownlint
    steps:
      - name: Run markdownlint
        uses: actionshub/markdownlint@v3.1.4

  golint-pr:
    runs-on: ubuntu-latest
    name: PR - GO lint
    steps:
      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2